### ISSUE TITLE
GAMS Editor - Add Bamboo as New Species Type

### ISSUE THREAD

**Issue by slmessier** [slmessier/eGIS---ASSET-DATA-WAREHOUSE#26]
From: Laurie Goudy
Sent: ‎12/‎29/‎2014 10:47 AM
To: Brad Spittel; Joseph Benedetta
Subject: invasive species: add Bamboo as a species name
Brad and Joe,
 
OED, Kevin, would like to **add ‘Bamboo’ to the list of species in the table ‘LU_IS_SPECIES_NAME’**?  They’ve been going a lot of work trying to control bamboo and it would be good to get it captured in eGIS.  What are the impacts to adding this to the LU table?  Any widget updates needed?
 
 
Thank you,

**Comment by slmessier** [comment]
The only **(2) expected technical updates** that will be required will be to **(1) add the new value to the list within the existing look-up table - LU_IS_SPECIES_NAME**, and **(2) update the drop downs on the Reports tab** to include the new value.

We do not foresee any contingencies in code at this time, and don’t anticipate updates to any web service. However widget functionality should be tested after implementing the new value in order to validate this understanding. 

Expected level-of-effort:
1. **6-8 hrs should be reserved to implement** at KCI-DEV, and then deploy at SHA test.  However, if expectations remain as outlined above, **only 1-2 hours are expected to be required.** 
2. **1-2 hours would be sufficient to test** across both environments. 
3. **~2 hours would be required to coordinate push to production and then test/validate.**

**Development will be able to start immediately.**

**Comment by TaraF** [comment]
Update: A small update to the Flex code is needed for updating the drop downs on the Reports tab.

**Comment by ladejobi** [comment]
Full regression against the new species value is successful in KCI Dev. The team will coordinate making this updates in SHA Dev and initiate testing in that environment.

**Comment by slmessier** [comment]
Greetings Joe,

The update to add "Bamboo" as a new species type has been implemented and tested succssfully in the SHA-DEV environment. 

**Note that we have also added 2015 as a new value for survey year within this request**

**Please test and provide confirmation via GitHub. Assuming that you are able to confirm we will coordinate to push into SHA-PRODUCTION.**

**Comment by jbenedetta** [comment]
If Possible, can the Species Name pull down menus be alphabetized.  Other that, I have tested and confirm the addition.

**Comment by TaraF** [comment]
Hi Joe and Scott,

Species Name drop down has been alphabetized.  Please test in shagbdapp.

-Tara

**Comment by jbenedetta** [comment]
Looks good, Thanks

Joseph Benedetta
Maryland State Highway Administration
Office of Planning & Preliminary Engineering
Data Services Engineering Division
410-545-5633
jbenedetta@sha.state.md.us<blocked::mailto:jbenedetta@sha.state.md.us>

**Comment by slmessier** [comment]
Tested successfully in SHA DEV after implementing the alphabetized list of values within Species Dropdown.

Push to production will be coordinated with John S.

**Comment by slmessier** [comment]
An unforeseen related issue was occurring exclusively with the report noted below. Specifically, the results of the report did not include the expected records when year = 2015.
![image](https://cloud.githubusercontent.com/assets/4098544/5761959/f4f5ddd0-9cac-11e4-9a74-608be329308d.png)

This issue has been fully investigated and resolved.

This issue will be closed.
