### ISSUE TITLE
Park and Ride Editor - Web Service Error Message - IOError #2036

### ISSUE THREAD

**Issue by slmessier** [slmessier/eGIS---ASSET-DATA-WAREHOUSE#28]
From: Joseph Benedetta [mailto:JBenedetta@sha.state.md.us] 
Sent: Thursday, July 09, 2015 7:33 AM
To: Scott Messier
Cc: Brad Spittel; John Shiu (john.shiu@ecointegration.com)
Subject: Park and Ride Issues

Good morning gentlemen,

The past couple of days there has been several people working in the PNR widget at one time.  Everyone has reported that the pop up screen below pops up at random times.

![image](https://cloud.githubusercontent.com/assets/4098544/8595865/bd8bb558-2619-11e5-94be-a3e7efe009be.png)
 
I have personally seen it after adding a survey and then clicking the save button.  It doesn’t happen all the time.  I did notice that even though the error is shown, the data still looks like it has been added.

**Comment by TaraF** [comment]
I think this issue might be a combination of DB issue and webservice error, based on what Joe is indicating above.

The URL / service that is causing the 500 error is:  http://shagbegis1/ADWPNRAPI/api/PNR/GetSurveyByLot?format=xml&browsernocache=Thu%20Jul%209%2009%3A35%3A03%20GMT%2D0400%202015&P%5FLot%5FId=107

**Comment by johnshiu** [comment]
I believe this is resolved now, although it's hard to test as it's intermittent. Concurrent reads to the same file were causing some locking issues, and I've made updates to the service code to avoid this.

Joe, please let us know if you still encounter this error, and I will investigate further.

**Comment by jbenedetta** [comment]
Looks like the issue has been resolved. Thanks
