### ISSUE TITLE
Park and Ride Editor - Web Service Error for PNR Facility MD 16 & MD 335

### ISSUE THREAD

**Issue by slmessier** [slmessier/eGIS---ASSET-DATA-WAREHOUSE#29]
From: Joseph Benedetta [mailto:JBenedetta@sha.state.md.us] 
Sent: Thursday, July 09, 2015 7:33 AM
To: Scott Messier
Cc: Brad Spittel; John Shiu (john.shiu@ecointegration.com)
Subject: Park and Ride Issues

Good morning gentlemen,
……
Another issue I see has to do with one record.  Not sure what happened.  This pops up after I click on the PNR lot to see the attributes. I deleted the lot then added a new one, however when I tried to add the pavement evaulation it wouldn’t load.  I changed the lot id number back to the original one (107)  in the database table and got the the pop the pop up again.

LOT ID - 107
MD 16 @ MD 335 in Dorchester County
![image](https://cloud.githubusercontent.com/assets/4098544/8595901/074a795e-261a-11e5-86bb-cdd401489fa7.png)

**Comment by TaraF** [comment]
I think this issue might be a combination of DB issue and webservice error, based on what Joe is indicating above, specific to this lot id.

The URL / service that is causing the 500 error is:  http://shagbegis1/ADWPNRAPI/api/PNR/GetSurveyByLot?format=xml&browsernocache=Thu%20Jul%209%2009%3A35%3A03%20GMT%2D0400%202015&P%5FLot%5FId=107

**Comment by johnshiu** [comment]
This should be fixed now; it was related to a percentage calculation error.

**Comment by jbenedetta** [comment]
Looks like the issue has been resolved. Thanks.
